# Generated by Django 4.2.2 on 2023-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0002_techsession_event_date_timeslot_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='day1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='day2',
            field=models.BooleanField(default=False),
        ),
    ]
