# Generated by Django 4.2.2 on 2023-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0003_room_day1_room_day2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handsonlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('max_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HandsonlabApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handsonlab', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
