# Generated by Django 4.2.2 on 2023-06-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0004_handsonlab_handsonlabapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsession',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
